// Code generated by swaggo/swag. Overwritten during Docker build.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/movies": {
            "get": {
                "description": "Returns all movies stored in the database",
                "produces": ["application/json"],
                "tags": ["movies"],
                "summary": "List all movies",
                "responses": {
                    "200": {"description": "OK", "schema": {"type": "array", "items": {"$ref": "#/definitions/httphandler.MovieResponse"}}},
                    "500": {"description": "Internal Server Error", "schema": {"$ref": "#/definitions/httphandler.ErrorResponse"}}
                }
            },
            "post": {
                "description": "Adds a new movie to the database",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["movies"],
                "summary": "Create a movie",
                "parameters": [{"description": "Movie payload","in": "body","name": "movie","required": true,"schema": {"$ref": "#/definitions/httphandler.CreateMovieRequest"}}],
                "responses": {
                    "201": {"description": "Created","schema": {"$ref": "#/definitions/httphandler.MovieResponse"}},
                    "400": {"description": "Bad Request","schema": {"$ref": "#/definitions/httphandler.ErrorResponse"}},
                    "500": {"description": "Internal Server Error","schema": {"$ref": "#/definitions/httphandler.ErrorResponse"}}
                }
            }
        },
        "/movies/{id}": {
            "get": {
                "description": "Returns a single movie by its MongoDB ObjectID",
                "produces": ["application/json"],
                "tags": ["movies"],
                "summary": "Get a movie by ID",
                "parameters": [{"description": "Movie ObjectID","in": "path","name": "id","required": true,"type": "string"}],
                "responses": {
                    "200": {"description": "OK","schema": {"$ref": "#/definitions/httphandler.MovieResponse"}},
                    "404": {"description": "Not Found","schema": {"$ref": "#/definitions/httphandler.ErrorResponse"}},
                    "500": {"description": "Internal Server Error","schema": {"$ref": "#/definitions/httphandler.ErrorResponse"}}
                }
            },
            "delete": {
                "description": "Removes a movie from the database by its MongoDB ObjectID",
                "produces": ["application/json"],
                "tags": ["movies"],
                "summary": "Delete a movie",
                "parameters": [{"description": "Movie ObjectID","in": "path","name": "id","required": true,"type": "string"}],
                "responses": {
                    "200": {"description": "OK","schema": {"$ref": "#/definitions/httphandler.SuccessResponse"}},
                    "404": {"description": "Not Found","schema": {"$ref": "#/definitions/httphandler.ErrorResponse"}},
                    "500": {"description": "Internal Server Error","schema": {"$ref": "#/definitions/httphandler.ErrorResponse"}}
                }
            }
        }
    },
    "definitions": {
        "httphandler.MovieResponse": {
            "type": "object",
            "properties": {
                "id": {"type": "string","example": "507f1f77bcf86cd799439011"},
                "external_id": {"type": "integer","example": 8},
                "title": {"type": "string","example": "Edison Kinetoscopic Record of a Sneeze (1894)"},
                "year": {"type": "string","example": "1894"}
            }
        },
        "httphandler.CreateMovieRequest": {
            "type": "object",
            "required": ["external_id","title","year"],
            "properties": {
                "external_id": {"type": "integer","example": 999},
                "title": {"type": "string","example": "My Movie"},
                "year": {"type": "string","example": "2024"}
            }
        },
        "httphandler.ErrorResponse": {
            "type": "object",
            "properties": {"error": {"type": "string","example": "movie not found"}}
        },
        "httphandler.SuccessResponse": {
            "type": "object",
            "properties": {"message": {"type": "string","example": "movie deleted successfully"}}
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Movies API",
	Description:      "REST API Gateway for the Movies microservice. Communicates with the movies-service via gRPC.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
